/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --shadows ./models/kart.glb
*/

import { useRef } from "react";
import { useGLTF, useProgress } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { damp } from "three/src/math/MathUtils.js";
import { useGameStore } from "../store.js";
import { Raycaster, Vector3 } from "three";
import { KartDust } from "./KartDust.jsx";
const raycaster = new Raycaster();

export function Kart({ speed, jumpOffset, inputTurn }) {
  const { nodes, materials } = useGLTF("/models/kart.glb");

  const wheel3 = useRef(null);
  const wheel2 = useRef(null);
  const wheel1 = useRef(null);
  const wheel0 = useRef(null);
  
  const wheel0Base = useRef(null)
  const wheel1Base = useRef(null)
  const wheel2Base = useRef(null)
  const wheel3Base = useRef(null)
  
  const groupRef = useRef(null);
  const frontWheels = useRef(null);
  const dustWheelStates = useRef([
    { position: new Vector3(), shouldEmit: false },
    { position: new Vector3(), shouldEmit: false },
    { position: new Vector3(), shouldEmit: false },
    { position: new Vector3(), shouldEmit: false },
  ]);

  const { progress } = useProgress();
  const bodyRef = useRef(null);
  const yRotation = useRef(0);
  const wheelRef = useRef(null);

  const groundMeshes = useRef([]);
  const setGroundPosition = useGameStore((state) => state.setGroundPosition);
  const setWheelPositions = useGameStore((state) => state.setWheelPositions);
  const { scene } = useThree();
  const direction = new Vector3(0, -1, 0)

  function rotateWheels(delta) {
    const rotationSpeed = speed.current * 0.01;
    wheel0.current.rotation.x += rotationSpeed;
    wheel1.current.rotation.x += rotationSpeed;
    wheel2.current.rotation.x += rotationSpeed;
    wheel3.current.rotation.x += rotationSpeed;

    yRotation.current = damp(
      yRotation.current,
      inputTurn.current,
      4, delta
    );

    frontWheels.current.rotation.y = yRotation.current;
    wheelRef.current.rotation.y = yRotation.current * Math.PI * 4;
  }

  function getGroundPosition(wheelBase, wheel, delta) {
    const origin = new Vector3();


  
    wheelBase.current.getWorldPosition(origin);
  
    raycaster.set(origin, direction);
    raycaster.far = 5;
    raycaster.firstHitOnly = true;
    raycaster.layers.set(1);
  
    const intersects = raycaster.intersectObjects(scene.children, true);
  
    if (intersects.length > 0) {
      const hit = intersects[0];
      if (hit.object.name.includes("ground")) {
        const safeY = Math.max(
          hit.point.y + 0.78 + jumpOffset.current,
          wheel.current.position.y - 0.1
        );
        wheel.current.position.y = safeY;

        wheel.current.lastSafeY = safeY;
      }

      wheel.current.isOnDirt =
        hit.object.name.includes("dirt") &&
        speed.current > 5 &&
        jumpOffset.current === 0;
    } else {
      if (typeof wheel.current.lastSafeY === "number") {
        wheel.current.position.y = damp(
          wheel.current.position.y,
          wheel.current.lastSafeY,
          4,
          delta
        );
      }
    }
  }

  function getWheelPositions() {
    const wheelPositions = [wheel0, wheel1, wheel2, wheel3].map(
      (wheel, index) => {
        const position = wheel.current.getWorldPosition(new Vector3());
        const localPos = wheel.current.position;
        dustWheelStates.current[index].position = localPos;
        dustWheelStates.current[index].shouldEmit = wheel.current.isOnDirt;

        return position;
      },
    );
    return wheelPositions;
  }

  function moveAndRotateKart(wheelPositions) {
    const a = wheelPositions[0];
    const b = wheelPositions[1];
    const c = wheelPositions[2];
    const d = wheelPositions[3];

    const pitch = (c.y + d.y - (a.y + b.y)) * 0.5;
    const roll = (b.y - a.y + d.y - c.y) * 0.5;

    const averageYPos = 0.65 + (a.y + b.y + c.y + d.y) / 4;
    setGroundPosition(averageYPos);

    bodyRef.current.rotation.x = pitch;

    // bodyRef.current.rotation.z = roll;

    bodyRef.current.position.y = averageYPos + jumpOffset.current * 0.1;
  }
  useFrame((_, delta) => {
    if (wheel0.current && wheel1.current && wheel2.current && wheel3.current) {
      if (groundMeshes.current.length < 2) {
        scene.traverse((obj) => {
          if (
            obj.isMesh &&
            obj.name.includes("ground") &&
            obj.geometry.boundsTree
          ) {
            groundMeshes.current.push(obj);
          }
        });
      }
      rotateWheels(delta);

      getGroundPosition(wheel0Base, wheel0, delta);
      getGroundPosition(wheel1Base, wheel1, delta);
      getGroundPosition(wheel2Base, wheel2, delta);
      getGroundPosition(wheel3Base, wheel3, delta);

      const wheelPositions = getWheelPositions();

      setWheelPositions([...wheelPositions, bodyRef.current]);
      moveAndRotateKart(wheelPositions, delta);

      bodyRef.current.isDrifting = false;
    }
  });

  return (
    <group
      key={progress}
      ref={groupRef}
      dispose={null}
      position-y={-0.5}
      scale={1}
      rotation-y={Math.PI}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body.geometry}
        material={materials.m_Body}
        ref={bodyRef}
      >
        <group ref={wheel2Base} position={[-0.77, 0, -0.7]} />
        <group ref={wheel3Base} position={[0.77, 0, -0.7]} />
        <group ref={wheel1Base} position={[0.7, 0, 0.7]} />
        <group ref={wheel0Base} position={[-0.7, 0, 0.7]} />
        <KartDust wheelStates={dustWheelStates.current} />
        <mesh
          ref={wheelRef}
          castShadow
          receiveShadow
          geometry={nodes.d_wheel.geometry}
          material={materials.m_Body}
          position={[0, 0.355, 0.542]}
          rotation={[-1.134, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.booster.geometry}
          material={materials.m_Body}
          position={[0, 0.25, -0.55]}
          rotation={[0.279, 0, 0]}
        />
      </mesh>

      <mesh
        ref={wheel2}
        castShadow
        receiveShadow
        geometry={nodes.wheel_2.geometry}
        material={materials.m_Tire}
        position={[-0.77, -0.137, -0.7]}
        layers={1}
      />
      <mesh
        ref={wheel3}
        castShadow
        receiveShadow
        geometry={nodes.wheel_3.geometry}
        material={materials.m_Tire}
        position={[0.77, -0.137, -0.7]}
        layers={1}
      />
      <group ref={frontWheels}>
        <mesh
          ref={wheel1}
          castShadow
          receiveShadow
          geometry={nodes.wheel_1.geometry}
          material={materials.m_Tire}
          position={[0.7, -0.2, 0.7]}
          layers={1}
        />
        <mesh
          ref={wheel0}
          castShadow
          receiveShadow
          geometry={nodes.wheel_0.geometry}
          material={materials.m_Tire}
          position={[-0.7, -0.2, 0.7]}
          layers={1}
        />
      </group>

      {/* <mesh castShadow receiveShadow geometry={nodes.shape.geometry} material={materials['default']} /> */}
    </group>
  );
}

useGLTF.preload("/models/kart.glb");
