/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --shadows --instance new-oval-track.glb 
Files: new-oval-track.glb [5.09MB] > /Users/chaseashton/Developer/Mario-Kart-Trainer/public/models/new-oval-track-transformed.glb [402.18KB] (92%)
*/

import React, {useRef, useEffect, useMemo } from 'react'
import { useGameStore } from '../store'
import { useGLTF } from '@react-three/drei'

export function Track(props) {
  const { nodes, materials, scene } = useGLTF('./models/oval-track-transformed.glb')
  const trackRef = useRef(null)
  const trackOffset = useGameStore((state) => state.trackOffset)
  const basePosition = useMemo(() => [75, -0.9, -165], [])
  const position = useMemo(
    () => [
      basePosition[0] + trackOffset.x,
      basePosition[1] + trackOffset.y,
      basePosition[2] + trackOffset.z,
    ],
    [basePosition, trackOffset]
  )
  
  const setTrackScene = useGameStore((state) => state.setTrackScene);
  useEffect(() => {
    if(setTrackScene && trackRef.current){
      setTrackScene(trackRef.current)
    }
  }, [setTrackScene])

  return (
    <group {...props} dispose={null} position={position}>
      <mesh layers={1} name={"tube"} castShadow receiveShadow geometry={nodes.Cylinder.geometry} material={materials['Material.002']} />
      <mesh ref={trackRef} layers={1} name={"road"} castShadow receiveShadow geometry={nodes.oval_road.geometry} material={materials.Road} />
      <mesh layers={1} name={"grass"} castShadow receiveShadow geometry={nodes.flat_plane.geometry} material={materials.plane} />
      <mesh layers={1} name={"finishline"} castShadow receiveShadow geometry={nodes.finish_line.geometry} material={materials.finish_line} />
      <mesh layers={1} name={"mountains"} castShadow receiveShadow geometry={nodes.Cylinder004.geometry} material={materials.snowcap_1} />
      <mesh layers={1} name={"mountains"} castShadow receiveShadow geometry={nodes.Cylinder004_1.geometry} material={materials.mountain_1} />
      <mesh layers={1} name={"finishline"} castShadow receiveShadow geometry={nodes.Object_6001.geometry} material={materials.finish_sign_01} />
      <mesh layers={1} name={"finishline"} castShadow receiveShadow geometry={nodes.Object_6001_1.geometry} material={materials.finish_sign_02} />
      <mesh layers={1} name={"finishline"} castShadow receiveShadow geometry={nodes.Object_6001_2.geometry} material={materials.finish_sign_03} />
    </group>
  )
}

useGLTF.preload('./models/oval-track-transformed.glb')
