/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --shadows --instance practice-tracks-1.glb 
Files: practice-tracks-1.glb [105.53KB] > /Users/chaseashton/Developer/Mario-Kart-Trainer/public/models/practice-tracks-1-transformed.glb [8.26KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useGameStore } from "../store";

export function Track(props) {
  const { nodes, materials } = useGLTF('/models/practice-tracks-1-transformed.glb')
  const trackRef = useRef(null);
  const setTrackScene = useGameStore((s) => s.setTrackScene);

  useEffect(() => {
    if (trackRef.current) setTrackScene?.(trackRef.current);
  }, [setTrackScene]);

  return (
    <group {...props} dispose={null} position={[0,0,0]} scale={1}>
      <mesh 
        ref={tracker}
        layers={1}
        name="ground"
        castShadow 
        receiveShadow 
        geometry={nodes.BézierCircle.geometry} 
        material={nodes.BézierCircle.material} />
    </group>
  )
}

useGLTF.preload('./models/practice-tracks-1-transformed.glb')
