/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --shadows --instance practice-tracks-1.glb 
Files: practice-tracks-1.glb [105.53KB] > /Users/chaseashton/Developer/Mario-Kart-Trainer/public/models/practice-tracks-1-transformed.glb [8.26KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/practice-tracks-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.BézierCircle.geometry} material={nodes.BézierCircle.material} />
    </group>
  )
}

useGLTF.preload('/practice-tracks-1-transformed.glb')
