/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --shadows --instance straight-track.glb 
Files: straight-track.glb [7.17MB] > /Users/chaseashton/Developer/Mario-Kart-Trainer/public/models/straight-track-transformed.glb [532.6KB] (93%)
*/

import React, {useRef, useEffect } from 'react'
import { useGameStore } from '../store'
import { useGLTF } from '@react-three/drei'

export function Track(props) {
    const { nodes, materials, scene } = useGLTF('./models/straight-track-transformed.glb')
    const trackRef = useRef(null)
    
    const setTrackScene = useGameStore((state) => state.setTrackScene);
    useEffect(() => {
      if(setTrackScene && trackRef.current){
        setTrackScene(trackRef.current)
      }
    }, [setTrackScene])

  return (
    <group {...props} dispose={null}>
      <mesh name="mountains" layers={1} castShadow receiveShadow geometry={nodes.Mountains.geometry} material={materials.Mountains} />
      <mesh ref={trackRef} name="road" layers={1} castShadow receiveShadow geometry={nodes.Road.geometry} material={materials.Road} />
      <mesh name="wall" layers={1} castShadow receiveShadow geometry={nodes.Walls.geometry} material={materials.Wall} />
    </group>
  )
}

useGLTF.preload('./models/straight-track-transformed.glb')
